### ISSUE TITLE
Upgrade version of @narative/gatsby-theme-novela to 0.13.2

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela-example#6]
This is the latest version on npm, this example should be updated.

I tried the newest version (0.13.2) and I get errors, but 0.11.2 works :/ My project is set up the same as this example so it maybe is a config which is broken.

**Comment by brotzky** [comment]
What errors are you getting?

**Comment by aleccool213** [comment]
https://github.com/aleccool213/blog/tree/novela-theme-0.13.2

![Screenshot at Jan 17 12-49-42](https://user-images.githubusercontent.com/6475934/72634112-e9f6e100-3927-11ea-8a2a-3175e40b0876.png)

**Comment by brotzky** [comment]
Thank you! Will check it out.

**Comment by aleccool213** [comment]
Fixed this by specifying:

```
        sources: {
          local: true,
          contentful: false
        }
```

in gatsby-config.js
