### ISSUE TITLE
@narative/gatsby-theme-novela: ^0.13.2 build error

### ISSUE THREAD

**Issue by zuqini** [narative/gatsby-theme-novela-example#7]
For ^0.13.2, the build always returns the following error:
```
You must have at least one Author and Post. As reference you can view the
    example repository. Look at the content folder in the example repo.
    https://github.com/narative/gatsby-theme-novela-example
```
even though the folder structure is properly set up.

Downgrading the version to ^0.11.3 fixes the issue.

## To reproduce
1. clone the gatsby-theme-novela-example repo.
1. upgrade @narative/gatsby-theme-novela version to 0.13.2
1. `npm install`
1. `gatsby develop`

**Comment by brotzky** [comment]
hey thanks :) will check it out this weekend. major bug!

**Comment by zuqini** [comment]
I had a chance to take a quick look at it and sent a quick fix. Let me know if it looks good!

**Comment by slorber** [comment]
can confirm issue, and 0.11.3 workaround

**Comment by brotzky** [comment]
you have to explicitly set Local now. maybe I should've made this a major bump...

```
       sources: {
          local: true,
          contentful: false
        }
```

Sorry for the confusion!!
