### ISSUE TITLE
How do I add custom logo?

### ISSUE THREAD

**Issue by m-sio** [narative/gatsby-theme-novela-example#8]
I have read the docs for the main repo, but I dont understand how to add logo to this example.

Thanks fo the help

**Comment by brotzky** [comment]
Make sure oyu understand Component Shadowing for Gatsby Themes first.

Here is an example of a real project that has replaced the logo:
https://github.com/caldera-digital/platform/blob/2a9961d7cc3f84bb2d13c24c1d5c03a519a49fef/projects/caldera-www/src/%40narative/gatsby-theme-novela/components/Logo/index.js

You must create the folders `@narative/gatsby-theme-novela/components/Logo/index.js`
and then place your SVG into it.
